import js from '@eslint/js';
import nextjs from '@next/eslint-plugin-next';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        browser: true,
        node: true,
        es2021: true,
        jest: true,
        process: true,
        console: true,
        global: true,
        URLSearchParams: true,
        Buffer: true,
        __dirname: true,
        __filename: true,
        setImmediate: true,
        clearImmediate: true,
        URL: true,
        performance: true,
        IntersectionObserver: true,
        PerformanceObserver: true,
        HTMLElement: true,
        HTMLDivElement: true,
        HTMLButtonElement: true,
        HTMLInputElement: true,
        HTMLTextAreaElement: true,
        HTMLTableElement: true,
        HTMLTableSectionElement: true,
        HTMLTableRowElement: true,
        HTMLTableCellElement: true,
        HTMLTableCaptionElement: true,
        HTMLUListElement: true,
        HTMLLIElement: true,
        HTMLSpanElement: true,
        HTMLParagraphElement: true,
        EventListener: true,
        AddEventListenerOptions: true,
        MouseEvent: true,
        Node: true,
        NodeJS: true,
        document: true,
        window: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        sessionStorage: true,
        localStorage: true,
        React: true,
        describe: true,
        it: true,
        expect: true,
        module: true,
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react: react,
      'react-hooks': reactHooks,
      '@next/next': nextjs,
    },
    rules: {
      ...typescript.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': 'warn',
      'no-undef': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
    },
  },
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'public/sw.js',
      'public/workbox-*.js',
      'dist/**',
      'build/**',
      'coverage/**',
      '**/*.config.js',
      '**/*.config.ts',
      '**/*.setup.js',
      '**/*.setup.ts',
      'next-env.d.ts',
    ],
  },
];
