import type { Winner } from './types';

// Mock data fallback (enhanced with sponsor info)
export const getMockWinners = (): Winner[] => [
  {
    id: '1',
    userId: 'user1',
    gameId: 'tech-lottery-2024',
    ticketId: 'ticket_1',
    prizeId: 'prize_1',
    prizeType: 'PRODUCT',
    prizeValue: 3999,
    currency: 'USD',
    prizeName: 'TECH BUNDLE',
    prizeDescription:
      'Premium tech bundle featuring the latest iPhone 15 Pro Max and MacBook Pro with M3 chip.',
    prizeImage: '/en/images/winner1.png',
    isClaimed: false,
    claimedAt: undefined,
    claimMethod: undefined,
    status: 'PENDING',
    createdAt: new Date('2024-12-01').getTime(),
    updatedAt: new Date('2024-12-01').getTime(),
  },
  {
    id: '2',
    userId: 'user2',
    gameId: 'fashion-lottery-2024',
    ticketId: 'ticket_2',
    prizeId: 'prize_2',
    prizeType: 'PRODUCT',
    prizeValue: 1500,
    currency: 'USD',
    prizeName: 'FASHION BUNDLE',
    prizeDescription: 'Designer clothing collection with premium accessories.',
    prizeImage: '/en/images/winner2.png',
    isClaimed: true,
    claimedAt: new Date('2024-11-25').getTime(),
    claimMethod: 'AUTOMATIC',
    status: 'CLAIMED',
    createdAt: new Date('2024-11-20').getTime(),
    updatedAt: new Date('2024-11-25').getTime(),
  },
  {
    id: '3',
    userId: 'user3',
    gameId: 'sports-lottery-2024',
    ticketId: 'ticket_3',
    prizeId: 'prize_3',
    prizeType: 'CASH',
    prizeValue: 2000,
    currency: 'USD',
    prizeName: 'CASH PRIZE',
    prizeDescription: 'Cash prize for sports equipment purchase.',
    isClaimed: true,
    claimedAt: new Date('2024-11-30').getTime(),
    claimMethod: 'MANUAL',
    status: 'DELIVERED',
    createdAt: new Date('2024-11-15').getTime(),
    updatedAt: new Date('2024-11-30').getTime(),
  },
];
