#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo " Running pre-commit checks..."

# Run lint-staged
echo " Running lint-staged..."
yarn lint-staged || exit 1

# Run prettier
echo " Running prettier..."
yarn prettier --check || exit 1

echo " Pre-commit checks passed!"
